/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-02 23:14:16
*/

module counter
(
  clk,
  rst,
  Q,
  sin,
  shift,
  sout,
  tck,
  test,
  _63_,
  \_63_.d ,
  _64_,
  \_64_.d ,
  _65_,
  \_65_.d ,
  _66_,
  \_66_.d ,
  \__uuf__._14_ ,
  \\__uuf__._14_.d ,
  \__uuf__._15_ ,
  \\__uuf__._15_.d ,
  \__uuf__._16_ ,
  \\__uuf__._16_.d ,
  \__uuf__._17_ ,
  \\__uuf__._17_.d 
);

  input _63_;
  output \_63_.d ;
  input _64_;
  output \_64_.d ;
  input _65_;
  output \_65_.d ;
  input _66_;
  output \_66_.d ;
  input \__uuf__._14_ ;
  output \\__uuf__._14_.d ;
  input \__uuf__._15_ ;
  output \\__uuf__._15_.d ;
  input \__uuf__._16_ ;
  output \\__uuf__._16_.d ;
  input \__uuf__._17_ ;
  output \\__uuf__._17_.d ;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] Q;
  wire [3:0] Q;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire \Q_din[0] ;
  wire \Q_din[1] ;
  wire \Q_din[2] ;
  wire \Q_din[3] ;
  wire \__BoundaryScanRegister_output__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.sout ;
  wire \__BoundaryScanRegister_output__2__.sout ;
  wire \__uuf__.__clk_source__ ;

  INVX1
  _31_
  (
    .A(rst),
    .Y(_00_)
  );


  INVX1
  _32_
  (
    .A(\Q_din[3] ),
    .Y(_12_)
  );


  INVX1
  _33_
  (
    .A(\Q_din[2] ),
    .Y(_13_)
  );


  INVX1
  _34_
  (
    .A(\Q_din[1] ),
    .Y(_14_)
  );


  INVX1
  _35_
  (
    .A(\Q_din[0] ),
    .Y(_15_)
  );


  INVX1
  _36_
  (
    .A(shift),
    .Y(_16_)
  );


  INVX1
  _37_
  (
    .A(clk),
    .Y(_17_)
  );


  NAND2X1
  _38_
  (
    .A(\Q_din[3] ),
    .B(shift),
    .Y(_18_)
  );


  OAI21X1
  _39_
  (
    .A(_15_),
    .B(shift),
    .C(_18_),
    .Y(_04_)
  );


  NAND2X1
  _40_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_output__0__.sout ),
    .Y(_19_)
  );


  OAI21X1
  _41_
  (
    .A(_14_),
    .B(shift),
    .C(_19_),
    .Y(_05_)
  );


  NAND2X1
  _42_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_output__1__.sout ),
    .Y(_20_)
  );


  OAI21X1
  _43_
  (
    .A(_13_),
    .B(shift),
    .C(_20_),
    .Y(_06_)
  );


  NAND2X1
  _44_
  (
    .A(shift),
    .B(\__BoundaryScanRegister_output__2__.sout ),
    .Y(_21_)
  );


  OAI21X1
  _45_
  (
    .A(_12_),
    .B(shift),
    .C(_21_),
    .Y(_07_)
  );


  NAND2X1
  _46_
  (
    .A(tck),
    .B(test),
    .Y(_22_)
  );


  OAI21X1
  _47_
  (
    .A(_17_),
    .B(test),
    .C(_22_),
    .Y(\__uuf__.__clk_source__ )
  );


  NAND2X1
  _48_
  (
    .A(\Q_din[1] ),
    .B(\Q_din[0] ),
    .Y(_23_)
  );


  NAND3X1
  _49_
  (
    .A(\Q_din[2] ),
    .B(\Q_din[1] ),
    .C(\Q_din[0] ),
    .Y(_24_)
  );


  NAND2X1
  _50_
  (
    .A(_00_),
    .B(_16_),
    .Y(_25_)
  );


  XNOR2X1
  _51_
  (
    .A(_12_),
    .B(_24_),
    .Y(_26_)
  );


  OAI22X1
  _52_
  (
    .A(_13_),
    .B(_16_),
    .C(_25_),
    .D(_26_),
    .Y(_11_)
  );


  XNOR2X1
  _53_
  (
    .A(_13_),
    .B(_23_),
    .Y(_27_)
  );


  OAI22X1
  _54_
  (
    .A(_14_),
    .B(_16_),
    .C(_25_),
    .D(_27_),
    .Y(_10_)
  );


  AOI21X1
  _55_
  (
    .A(\Q_din[1] ),
    .B(_16_),
    .C(\Q_din[0] ),
    .Y(_28_)
  );


  OAI21X1
  _56_
  (
    .A(_14_),
    .B(_15_),
    .C(_00_),
    .Y(_29_)
  );


  AOI21X1
  _57_
  (
    .A(_16_),
    .B(_29_),
    .C(_28_),
    .Y(_09_)
  );


  NAND2X1
  _58_
  (
    .A(shift),
    .B(sin),
    .Y(_30_)
  );


  OAI21X1
  _59_
  (
    .A(\Q_din[0] ),
    .B(_25_),
    .C(_30_),
    .Y(_08_)
  );


  INVX1
  _60_
  (
    .A(rst),
    .Y(_01_)
  );


  INVX1
  _61_
  (
    .A(rst),
    .Y(_02_)
  );


  INVX1
  _62_
  (
    .A(rst),
    .Y(_03_)
  );

  assign sout = _63_;
  assign \_63_.d  = _07_;
  assign \__BoundaryScanRegister_output__2__.sout  = _64_;
  assign \_64_.d  = _06_;
  assign \__BoundaryScanRegister_output__1__.sout  = _65_;
  assign \_65_.d  = _05_;
  assign \__BoundaryScanRegister_output__0__.sout  = _66_;
  assign \_66_.d  = _04_;
  assign \Q_din[0]  = \__uuf__._14_ ;
  assign \\__uuf__._14_.d  = _08_;
  assign \Q_din[1]  = \__uuf__._15_ ;
  assign \\__uuf__._15_.d  = _09_;
  assign \Q_din[2]  = \__uuf__._16_ ;
  assign \\__uuf__._16_.d  = _10_;
  assign \Q_din[3]  = \__uuf__._17_ ;
  assign \\__uuf__._17_.d  = _11_;
  assign Q = { \Q_din[3] , \Q_din[2] , \Q_din[1] , \Q_din[0]  };

endmodule

